version: '3.7'
services:
    react-api-template:
        container_name: react-api-template
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: example-db
        ports:
            - "6000:27017"
