version: "3"
services:
    express-react-ts-template:
        image: elyspio/express-react-ts-template
        container_name: express-react-ts-template
        restart: always
        volumes:
            - "./config/front/conf.js:/front/conf.js"
        environment:
            AUTHENTICATION_SERVER_URI: "https://elyspio.fr/authentication"
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=frontend"
            - "traefik.http.middlewares.express-react-ts-template-prefix.stripprefix.prefixes=/express-react-ts-template"
            - "traefik.http.routers.express-react-ts-template.middlewares=authentication-prefix@docker"
            - "traefik.http.routers.express-react-ts-template.rule=PathPrefix(`/express-react-ts-template`)"
            - "traefik.http.services.express-react-ts-template.loadbalancer.server.port=4000"
            - "traefik.http.routers.express-react-ts-template.entrypoints=http"
        networks:
            - express-react-ts-template
            - frontend

networks:
    express-react-ts-template:
        name: express-react-ts-template
    frontend:
        external: true
